name: Test parallel

on:
  push:


jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - name: Clone helm chart repository
        uses: actions/checkout@v3
        with:
          submodules: true


  setup-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Setup docker
        uses: docker/setup-docker-action@v4
      
  setup-task:
    runs-on: ubuntu-latest
    steps:
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Test task
        run: |
          task --version
          ls -la 
          command -v task

  test-things:
    needs:
      - setup-docker
      - setup-task
      - clone
    runs-on: ubuntu-latest
    steps:
      - name: Clone helm chart repository
        uses: actions/checkout@v3
        with:
          submodules: true


      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Test things
        run: |
          docker --version
          ls -la 
          command -v task
