name: Test parallel

on:
  push:


jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/lib/clone.yaml

  setup-task:
    runs-on: ubuntu-latest
    steps:
          

  test-things:
    needs:
      - setup-task
      - clone
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/lib/setup-task.yaml
      - name: Test things
        run: |
          task --version
          ls -la 
